export const avatarModelMap: Record<string, string> = {
  adventurer: "adventurer",
  avataaars: "avataaars",
  bigEars: "big-ears",
  bigSmile: "big-smile",
  bottts: "bottts",
  croodles: "croodles",
  funEmoji: "fun-emoji",
  icons: "icons",
  lorelei: "lorelei",
  micah: "micah",
  miniavs: "miniavs",
  notionists: "notionists",
  openPeeps: "open-peeps",
  personas: "personas",
  pixelArt: "pixel-art",
  thumbs: "thumbs",
};
